import {gettext as _} from 'resource:///org/gnome/shell/extensions/extension.js';

/**
 * @description gemini functions
 * @param {object} app
 */
export class FunctionsActivations {
    constructor(app) {
        this.app = app;

        this.assitname = ['aiva', this.app.userSettings.ASSIST_NAME];

        this.applist = [
            _('youtube'),
            _('chrome'),
            _('edge'),
            _('firefox'),
            _('terminal'),
            _('gnome'),
            _('settings'),
            _('monitor'),
            _('calculator'),
            _('gedit'),
            _('libreoffice'),
            _('firefox'),
            _('vscode'),
            _('code'),
            _('brave'),
            _('telegram'),
            _('spotify'),
            _('discord'),
            _('slack'),
            _('zoom'),
            _('teams'),
            _('meet'),
            _('evolution'),
            _('thunderbird'),
            _('filezilla'),
            _('winscp'),
            _('putty'),
            _('virtualbox'),
            _('vmware'),
            _('docker'),
            _('kubernetes'),
            _('steam'),
            _('origin'),
            _('epic'),
            _('battle.net'),
            _('gog'),
            _('itch.io'),
            _('lutris'),
            _('wine'),
            _('proton'),
            _('playonlinux'),
            _('appimage'),
            _('snap'),
            _('flatpak'),
            _('rpm'),
            _('deb'),
            _('tar'),
            _('zip'),
            _('rar'),
            _('7z'),
            _('pdf'),
            _('doc'),
            _('docx'),
            _('xls'),
            _('xlsx'),
            _('ppt'),
            _('pptx'),
            _('txt'),
            _('csv'),
            _('json'),
            _('xml'),
            _('html'),
            _('css'),
            _('js'),
            _('php'),
            _('py'),
            _('java'),
            _('c'),
            _('cpp'),
            _('go'),
            _('swift'),
            _('kotlin'),
            _('ruby'),
            _('perl'),
            _('python'),
            _('node'),
            _('npm'),
            _('yarn'),
            _('composer'),
            _('maven'),
            _('gradle'),
            _('ant'),
            _('git'),
            _('github'),
            _('gitlab'),
            _('bitbucket'),
            _('vscode'),
            _('sublime'),
            _('atom'),
            _('notepad++'),
            _('drive'),
            _('onedrive'),
            _('dropbox'),
            _('photos'),
            _('docs'),
            _('sheets'),
            _('slides'),
            _('forms'),
            _('translate'),
            _('calendar'),
            _('tasks'),
        ];

        this.open = [
            _('open'),
            _('launch'),
            _('start'),
            _('run'),
            _('load'),
            _('initialize'),
        ];

        this.read = [_('read'), _('read_var1'), _('read_var2')];

        this.clipboard = [
            _('clipboard text'),
            _('clipboard_text_var1'),
            _('text I copied'),
            _('what did I copy'),
            _('copied text'),
            _('my clipboard'),
            _("what's copied"),
            _('clipboard content'),
            _('just copied'),
            _('what I copied'),
            _('copied content'),
            _('clipboard data'),
            _('the clipboard'),
        ];

        this.browse = [
            _('open'),
            _('go to'),
            _('navigate'),
            _('visit'),
            _('check out'),
            _('pull up'),
            _('bring'),
            _('take me'),
            _('show me'),
            _('launch'),
            _('load'),
            _('find'),
            _('browse'),
            _('search'),
        ];

        this.site = [
            _('website'),
            _('site'),
            _('page'),
            _('webpage'),
            _('link'),
            _('url'),
            _('address'),
            _('blog'),
        ];

        this.preweather = [
            _('how is the'),
            _('what is the'),
            _("what's the"),
            _('how hot is it'),
            _('how cold is it'),
            _('is there'),
            _('will it'),
            _('do I need'),
            _('how warm is it'),
            _("how's the"),
            _('should I'),
            _('is the'),
            _('what time will it'),
            _('is it'),
            _('how long will it'),
            _('are there any'),
            _('will there be a'),
        ];

        this.weather = [
            _('weather'),
            _('temperature'),
            _('raining'),
            _('snowing'),
            _('windy'),
            _('forecast'),
            _('cloudy'),
            _('storm'),
            _('humidity'),
            _('rain'),
            _('snow'),
            _('umbrella'),
            _('jacket'),
            _('warm'),
            _('foggy'),
            _('freezing'),
            _('high for today'),
            _('low for today'),
            _('a coat'),
            _('wind'),
            _('stormy'),
            _('drizzling'),
            _('thunder'),
            _('lightning'),
            _('mild'),
            _('air pressure'),
            _('heatwave'),
            _('chilly'),
            _('overcast'),
            _('clear'),
            _('hot'),
            _('outside'),
            _('hurricane'),
            _('uv index'),
            _('sunny'),
            _('hail'),
            _('frost'),
            _('cold'),
            _('dew point'),
            _('visibility'),
        ];

        console.log('Functions loaded.');
    }
}
