import {gettext as _} from 'resource:///org/gnome/shell/extensions/extension.js';

/**
 * @description gemini functions
 * @param {object} app
 */
export class FunctionsActivations {
    constructor(app) {
        this.app = app;

        this.assitname = ['aiva', this.app.userSettings.ASSIST_NAME];

        this.readClipboard = [
            _('read the copied text'),
            _("what's in the clipboard"),
            _('read the clipboard content'),
            _('read the text I copied'),
            _('what did I copy'),
            _('show me the copied text'),
            _("what's in my clipboard"),
            _("read what's copied"),
            _('tell me the clipboard text'),
            _('can you read the copied text'),
            _('could you show the clipboard content'),
            _('read the text from the clipboard'),
            _('display the copied text'),
            _('show the clipboard content'),
            _('can you access the clipboard'),
            _('read what I just copied'),
            _('what text is on the clipboard'),
            _('tell me what I copied'),
            _('fetch the clipboard content'),
            _('read the copied content'),
            _('read the clipboard data'),
            _("show me what's on the clipboard"),
            _('can you display the copied text'),
            _('read my copied text'),
            _('what is the copied text'),
            _('can you fetch the clipboard text'),
            _('read the clipboard for me'),
            _('what text is stored in the clipboard'),
            _('show the latest copied text'),
            _('read the most recent clipboard content'),
        ];

        this.cmd = [
            _('open the app'),
            _('open the application'),
            _('launch the app'),
            _('launch the software'),
            _('start the app'),
            _('start the application'),
            _('run the app'),
            _('run the software'),
            _('open this program'),
            _('launch this program'),
            _('start the program'),
            _('can you open the app'),
            _('could you open the software'),
            _('bring up the app'),
            _('bring up the application'),
            _('fire up the app'),
            _('fire up the program'),
            _('please open the software'),
            _('please start the app'),
            _('run this application'),
            _('execute the program'),
            _('load the app'),
            _('load the software'),
            _('boot up the app'),
            _('can you run this program'),
            _('could you launch this software'),
            _('open the snap'),
            _('launch the snap'),
            _('start the snap'),
            _('run the snap'),
            _('load the snap'),
            _('open the flatpak'),
            _('launch the flatpak'),
            _('start the flatpak'),
            _('run the flatpak'),
            _('load the flatpak'),
            _('fire up the software'),
            _('boot up this application'),
            _('pull up the app'),
            _('navigate to the app'),
            _('turn on the software'),
            _('access the app'),
            _('can you open this tool'),
            _('could you start this application'),
            _('execute this tool'),
            _('please run this software'),
            _('activate the app'),
            _('initialize the software'),
            _('change the wallpaper'),
            _('set a new desktop background'),
            _('enable dark mode'),
            _('switch to light mode'),
            _('adjust the screen brightness'),
            _('change the display resolution'),
            _('enable fractional scaling'),
            _('customize the dock position'),
            _('hide the dock'),
            _('show the dock'),
            _('change the dock size'),
            _('enable auto-hide for the dock'),
            _('disable auto-hide for the dock'),
            _('add an app to the favorites'),
            _('remove an app from the favorites'),
            _('customize the keyboard shortcuts'),
            _('change the font size'),
            _('enable animations'),
            _('disable animations'),
            _('adjust the workspace settings'),
            _('change the number of workspaces'),
            _('rename a workspace'),
            _('configure the touchpad settings'),
            _('enable tap-to-click'),
            _('disable tap-to-click'),
            _('enable natural scrolling'),
            _('disable natural scrolling'),
            _('change the default shell theme'),
            _('apply a new GTK theme'),
            _('change the icon theme'),
            _('reset GNOME settings to default'),
            _('turn on night light'),
            _('turn off night light'),
            _('schedule night light'),
            _('customize the power settings'),
            _('set the screen to never lock'),
            _('change the lock screen background'),
            _('enable notifications'),
            _('disable notifications'),
            _('install GNOME extensions'),
            _('remove a GNOME extension'),
            _('enable a GNOME extension'),
            _('disable a GNOME extension'),
            _('list all GNOME extensions'),
            _('check the status of GNOME extensions'),
            _('update the GNOME extensions'),
            _('restart GNOME shell'),
            _('change the primary display'),
            _('disable secondary monitor'),
            _('enable secondary monitor'),
            _('mirror the displays'),
            _('extend the displays'),
            _('set the display refresh rate'),
            _('adjust the sound volume'),
            _('enable do not disturb mode'),
            _('disable do not disturb mode'),
            _('change the default browser'),
            _('set the default terminal'),
            _('enable accessibility features'),
            _('disable accessibility features'),
            _('set a new keyboard layout'),
            _('enable the on-screen keyboard'),
            _('disable the on-screen keyboard'),
        ];

        this.browseWeb = [
            _('open the website'),
            _('open the page'),
            _('open the blog'),
            _('go to the website'),
            _('go to the page'),
            _('go to the blog'),
            _('navigate to the site'),
            _('navigate to the page'),
            _('visit the website'),
            _('visit the page'),
            _('open this link'),
            _('go to this URL'),
            _('open the URL'),
            _('check out this site'),
            _('pull up the website'),
            _('can you open the site'),
            _('could you open the page'),
            _('bring up the website'),
            _('take me to the site'),
            _('take me to the page'),
            _('show me the website'),
            _('show me the page'),
            _('launch the site'),
            _('launch the page'),
            _('visit this link'),
            _('can you navigate to the URL'),
            _('please open this site'),
            _('please visit the page'),
            _('open this blog for me'),
            _('take me to this blog'),
            _('show me the link'),
            _('can you load this page'),
            _('go to this link'),
            _('open a new tab with this site'),
            _('navigate to this link'),
            _('find this website for me'),
            _('bring up the blog'),
            _('open a tab for this page'),
            _('could you visit this link'),
            _('click this link for me'),
            _('take me to this URL'),
            _('browse to the website'),
            _('open this webpage'),
            _('find this page online'),
            _('show me this site'),
        ];

        this.weather = [
            _('how is the weather'),
            _('what is the temperature'),
            _("what's the weather like"),
            _('is it raining'),
            _('is it sunny'),
            _('is it snowing'),
            _('is it windy'),
            _("what's the forecast"),
            _("what's the weather forecast"),
            _('how hot is it outside'),
            _('how cold is it outside'),
            _('is it cloudy'),
            _('is there a storm coming'),
            _("what's the humidity level"),
            _('is it going to rain today'),
            _('will it snow tomorrow'),
            _("what's the weather like this week"),
            _('do I need an umbrella'),
            _('do I need a jacket'),
            _('how warm is it outside'),
            _('is there a chance of rain'),
            _('is it foggy'),
            _('is it freezing'),
            _("what's the high for today"),
            _("what's the low for today"),
            _("how's the weather right now"),
            _('should I bring a coat'),
            _("what's the wind speed"),
            _('is it stormy'),
            _('is it drizzling'),
            _('is there thunder'),
            _('is it lightning'),
            _('is it mild outside'),
            _("what's the air pressure"),
            _('is there a heatwave'),
            _('is it chilly'),
            _('is it overcast'),
            _('is the weather clear'),
            _('will it be hot this weekend'),
            _('is it safe to go outside'),
            _('is there a hurricane warning'),
            _("what's the UV index today"),
            _('what time will it rain'),
            _('is it good weather for a walk'),
            _('is it safe to drive in this weather'),
            _('will it be sunny later'),
            _('how long will it rain'),
            _('are there any weather alerts'),
            _('will it clear up later'),
            _('should I expect hail'),
            _('will there be a frost tonight'),
            _('is there a cold front coming'),
            _("what's the dew point"),
            _("how's the visibility today"),
        ];

        this.words = [
            ...this.assitname,
            ...this.weather,
            ...this.readClipboard,
            ...this.browseWeb,
            ...this.cmd,
        ];

        console.log('Functions loaded.');
    }
}
